export type {
  AlertId,
  AnchorResolution,
  ChapterNo,
  CharacterId,
  Derived,
  EventSeq,
  ForeshadowId,
  IsoTimestamp,
  PlotLineId,
  Provenance,
  SettingId,
  StructuralEventId,
  TextAnchor,
  VolumeNo,
} from "./primitives.js";

export type {
  C5Declaration,
  CharacterPresencePayload,
  CharacterStateChangedPayload,
  EventEnvelope,
  EventKind,
  EventOrigin,
  EventWeight,
  ForeshadowAbandonedPayload,
  ForeshadowPlantedPayload,
  ForeshadowRescheduledPayload,
  ForeshadowResolvedPayload,
  ForeshadowVisibility,
  ForeshadowWeight,
  PlotAdvancePayload,
  PlotEventPayload,
  RelationChangedPayload,
  RelationKind,
  ResolutionCompleteness,
  StructuralEvent,
  StructuralEventOf,
  StructuralEventPayload,
  StructuralEventType,
} from "./events.js";
export { C5_LIMITS } from "./events.js";

export type {
  AddressForm,
  CardChangeProposal,
  CharacterAttribute,
  CharacterCard,
  CharacterProfile,
  CharacterState,
  CharacterTier,
  EmotionalExpression,
  SpeechProfile,
  SpeechRegister,
  VitalStatus,
  VoiceCheckChannel,
  VoiceCheckSpec,
} from "./character.js";
export { VOICE_CHECKS } from "./character.js";

export type {
  ChapterBeat,
  ChapterBudget,
  ChapterPlan,
  ChapterType,
  DensityRange,
  DetectionThresholds,
  GateFinding,
  GateLevel,
  Genre,
  OverflowAction,
  PipelineTier,
  PlannedEvent,
  PlannedResolution,
  Platform,
  SplitAdvice,
  WordBudget,
  WorkProfile,
} from "./beat.js";

export type {
  CacheMetrics,
  ContextSegment,
  L2AppendEntry,
  L2CharacterRow,
  L2ForeshadowRow,
  L2PlotLineRow,
  L2RebuildState,
  L2Renderer,
  L2Snapshot,
  L2SynopsisRow,
  SynopsisGranularity,
  VolumeBoundary,
} from "./l2.js";
export { L2_REBUILD_LIMITS, M1_CACHE_TARGETS } from "./l2.js";

export type {
  Alert,
  AlertAction,
  AlertCategory,
  AlertSubject,
  CharacterArc,
  ForeshadowStatus,
  ForeshadowTimelineItem,
  PlotLinePoint,
  PlotLineTrack,
  RelationEdge,
  RepairDirection,
} from "./projections.js";
export { DIRECTION_FACTORS, FATIGUE_FACTORS, HOMEPAGE_ALERT_LIMIT } from "./projections.js";
